name: check-count-actions
on:
  push:
    branches:
      - main
jobs:
  check-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Check count of app
        run: |
          git status
          line_count=$(find in -type f -exec grep app {} \; | wc -l)
          ret=$?
          echo "ret=${ret}"
          echo "line_count=${line_count}"
          if [ $line_count -eq 1 ]; then
            exit 0
          else
            exit 1
          fi
