name: check-count-actions
on:
  push:
    branches:
      - main
jobs:
  check-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check count of app
        run: |
          find in -type f -exec grep app {} \; | wc -l
          ret=$?
          echo "ret=${ret}"
          if [ $ret -eq 1 ]; then
            exit 0
          else
            exit 1
          fi
