name: poetry actions
on:
  push:
    branches:
      - main
jobs:
  check-count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Check command
        run: |
          python --version
          python3 --version
          poetry --version
